apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
data:
  RABBITMQ_DEFAULT_USER: 'roboshop'
  RABBITMQ_DEFAULT_PASS: 'roboshop123'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: db
  template:
    metadata:
      name: rabbitmq
      labels:
        component: rabbitmq
        project: roboshop
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: db 
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: db 
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672            