apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    component: mongodb
    project: roboshop
    tier: db
  annotations:
    purpose: this is mongodb manifest file.
  namespace: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      name: mongodb
      labels:
        component: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: jay1303/mongodb:v1
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    component: mongodb
    project: roboshop
    tier: db
  namespace: roboshop
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
  - port: 27017
    targetPort: 27017