apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: backend
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: backend
  annotations:
    description: This is catalogue microservice
  namespace: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: backend     
  template:
    metadata:
      name: catalogue
      labels:
        component: catalogue
        project: roboshop
        tier: backend 
    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:v1
        ports:
        - containerPort: 8080
        env:
        - configMapRef:
          name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: backend
  namespace: roboshop
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: backend
  ports:
  - port: 8080
    targetPort: 8080