apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: catalogue
      project: roboshop
      tier: app
  template:
    metadata:
      name: catalogue-pod
      labels: 
        pod: catalogue
        project: roboshop
        tier: app
      containers:
      - name: catalogue
        image: jay1303/catalogue:v1
---
apiVersion: apps/v1
kind: Service
metadata:
  name: catalogue
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app
  ports:
    - port: 8080
      targetPort: 8080