apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: db
  annotations:
    description: This is redis microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: db
  template:
    metadata:
      name: redis
      labels:
        component: redis
        project: roboshop
        tier: db
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: db
spec:
  selector:
    component: redis
    project: roboshop
    tier: db
  ports:
  - port: 6379
    targetPort: 6379